version: 0.0

files:
  - source: app.jar
    destination: /opt/myapp
  - source: scripts/
    destination: /opt/myapp/scripts

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 900
      runas: root

