springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

spring:

  profiles:
    include: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_schema: test

app:
  cors:
    allowed-origin: ${FRONTEND_ORIGIN:http://localhost:3000}
