spring:
  # 데이터베이스 연결 설정
  datasource:
    url: jdbc:mysql://localhost:3306/next_shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root # 본인의 MySQL 사용자 이름으로 변경
    password: 1234 # 본인의 MySQL 비밀번호로 변경
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA(Java Persistence API) 설정
  jpa:
    hibernate:
      # ddl-auto: update => Address.java 같은 엔티티 클래스가 변경되면, DB 테이블을 자동으로 업데이트 해줌 (개발 시 유용)
      ddl-auto: update
    properties:
      hibernate:
        # 실행되는 SQL 쿼리를 예쁘게 포맷팅해서 보여줌
        format_sql: true
    # 콘솔에 실행되는 SQL 쿼리를 보여줌
    show-sql: true